### ISSUE TITLE
Implement "unknown fish" identification feature

### ISSUE THREAD

**Issue by wengdg** [wengdg/reefnexus#18]

**Comment by bsogata** [comment]
Instead of having users type in the name of the fish species (which would be very difficult to do in the intended environment where this application would be used), users could select from a grid of images of the fish already known to be in the region.  If the fish does not match any of the species known to be in the location, a generic "Add Fish" button would allow users to input the necessary data.

**Comment by bsogata** [comment]
This appears to have been completed and can be closed.
